SugarAccount:
  id: 1
  name: SugarAccount
  adapter: SugarAccount
  app_id: 1
  limit: 100
 
SugarCase:
  id: 2
  name: SugarCase
  app_id: 1
  adapter: SugarCase
  limit: 100
 
SugarEmployee:
  id: 3
  name: SugarEmployee
  app_id: 1
  adapter: SugarEmployee
  limit: 100
  
SugarContact:
  id: 11
  name: SugarContact
  app_id: 1
  adapter: SugarContact
  limit: 100
  
SugarLead:
  id: 12
  name: SugarLead
  app_id: 1
  adapter: SugarLead
  limit: 100
  
SugarOpportunity:
  id: 13
  name: SugarOpportunity
  app_id: 1
  adapter: SugarOpportunity
  limit: 100
    
SugarMeeting:
  id: 14
  name: SugarMeeting
  app_id: 1
  adapter: SugarMeeting
  limit: 100
    
SugarCall:
  id: 15
  name: SugarCall
  app_id: 1
  adapter: SugarCall
  limit: 100
 
SugarCampaign:
  id: 16
  name: SugarCampaign
  app_id: 1
  adapter: SugarCampaign
  limit: 100
    
SugarProduct:
  id: 17
  name: SugarProduct
  app_id: 1
  adapter: SugarProduct
  limit: 100
      
SugarTeam:
  id: 18
  name: SugarTeam
  app_id: 1
  adapter: SugarTeam
  limit: 100
  
SugarUser:
  id: 19
  name: SugarUser
  app_id: 1
  adapter: SugarUser
  limit: 100
  
SugarQuote:
  id: 21
  name: SugarQuote
  app_id: 1
  adapter: SugarQuote
  limit: 100
 
Customer:
  id: 22
  name: Customer
  app_id: 2
  adapter: Customer
  url: http://rhostore.heroku.com/customers.json
  limit: 100
 
Product:
  id: 23
  name: Product
  app_id: 2
  adapter: Product
  url: http://rhostore.heroku.com/products.json
  limit: 100

