AeropriseCategory:
  id: 1
  name: AeropriseCategory
  adapter: AeropriseCategory
  app_id: 1
  limit: 10000000
  pollinterval: -1
  queuesync: 1

AeropriseRequest:
  id: 2
  name: AeropriseRequest
  adapter: AeropriseRequest
  app_id: 1
  limit: 10000000
  pollinterval: -1
  queuesync: 1

AeropriseSrd:
  id: 3
  name: AeropriseSrd
  adapter: AeropriseSrd
  app_id: 1
  limit: 10000000
  pollinterval: -1
  queuesync: 1

AeropriseUser:
  id: 4
  name: AeropriseUser
  adapter: AeropriseUser
  app_id: 1
  limit: 10000000
  pollinterval: -1

AeropriseWorklog:
  id: 5
  name: AeropriseWorklog
  adapter: AeropriseWorklog
  app_id: 1
  limit: 10000000
  pollinterval: 0 

